all:
  vars:
    vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: ~/.ssh/gitlab_deploy_key
    ansible_connection: ssh 
  children: 
    backend:
      hosts:
        51.250.82.82:
    frontend:
      hosts:
        51.250.82.82: 
