$ANSIBLE_VAULT;1.1;AES256
30613830356235336165303139396133666132663232313430653834666465353766613432313436
6263323066633437386437383134366534636161303232380a313530336636366332663264333665
66363162366236313735373662646662316633303465396330656163326266663331336234313639
6663383838306238350a396139333934383166616130316432656338356463333634373166303236
63323334613964373332303334646239666439646463643132633264363861653466323863663366
61663531336637353465333339306264326363393533653236346131353732316633663637626265
34306465666339656639613966386466663863353861363738623538383362313366356463303463
63646632323662313964316539326664393265333533373461653937343233663239663735386532
6237
