#ci бэк реп
stages:
  - deploy

deploy-backend-report:
  stage: deploy
  image: bitnami/kubectl
  script:
    - echo "$kubeconfig" > ~/.kube/config
    - envsubst < ./kubernetes/backend-report/secrets.yaml | kubectl apply -f -
    - kubectl apply -f ./kubernetes/backend-report/deployment.yaml
    - kubectl apply -f ./kubernetes/backend-report/service.yaml
    - rm -rf ~/.kube/config
  environment:
    name: k8s
    url: http://std-042-36.k8s.praktikum-services.tech